{% set name = "ufmt" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ufmt-{{ version }}.tar.gz
  sha256: d977f0fad0c054bd69518a4b5ca4af6e8f39960982c4f9fe719a1687aaf92638

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - ufmt = ufmt.cli:main

requirements:
  host:
    - python >=3.7
    - pip
    - flit-core >=3,<4
    - black >=20.8b0
    - moreorless >=0.4.0
    - usort >=1.0
    - tomlkit >=0.7.2
    - trailrunner >=1.2.1
  run:
    - python >=3.7
    - black >=20.8b0
    - click >=8.0
    - libcst >=0.4.0
    - moreorless >=0.4.0
    - tomlkit >=0.7.2
    - trailrunner >=1.2.1
    - typing-extensions >=4.0
    - usort >=1.0

test:
  imports:
    - ufmt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://ufmt.omnilib.dev
  summary: Safe, atomic formatting with black and Î¼sort
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dstoeckel
    - nicornk
