{% set name = "ufmt" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ufmt-{{ version }}.tar.gz
  sha256: ef0094a8ff554e978ddd7c27cf0c8e87e44ae70c55112ccb5c8c23b47f5467cd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - ufmt = ufmt.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3,<4
    - black >=20.8b0
    - moreorless >=0.4.0
    - usort >=1.0
    - tomlkit >=0.7.2
    - trailrunner >=1.2.1
  run:
    - python >={{ python_min }}
    - black >=20.8b0
    - click >=8.0
    - libcst >=0.4.0
    - moreorless >=0.4.0
    - tomlkit >=0.7.2
    - trailrunner >=1.2.1
    - typing-extensions >=4.0
    - usort >=1.0

test:
  imports:
    - ufmt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://ufmt.omnilib.dev
  summary: Safe, atomic formatting with black and Î¼sort
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dstoeckel
    - nicornk
